### ISSUE TITLE
Delay in loading CSS

### ISSUE THREAD

**Issue by SKAUL05** [codeforcauseorg/pledge#16]
### Description

When I open the site [Pledge](https://pledge.codeforcause.org/), there is a delay in loading CSS.
It takes close to 1s to load the CSS.

![Pledge_Issue](https://user-images.githubusercontent.com/13817417/83380878-c1feaa80-a3fc-11ea-9c1f-77a04b3729f3.gif)

**Comment by Abhishek-kumar09** [comment]
It is discussed here:
> If you're using a css-in-js library, you need to install its corresponding gatsby plugin to ensure that the css for pages is extracted and added to the generated HTML as otherwise, css isn't added until after the JS loads which causes the delay you see.

https://github.com/gatsbyjs/gatsby/issues/9902#issuecomment-438834341

**Comment by Abhishek-kumar09** [comment]
closed with https://github.com/codeforcauseorg/pledge/pull/45
