### ISSUE TITLE
Add interactive loader

### ISSUE THREAD

**Issue by darecoder1999** [codeforcauseorg/pledge#21]
Add an interactive loader that matches with the current theme of the webpage.

**Comment by anishghimire603** [comment]
Hello, I would like to work in this issue, can you suggest me ways to get started?

**Comment by manavgakhar** [comment]
Hi, I would like to work on this issue, can you suggest ways to get started?

**Comment by darecoder1999** [comment]
Hello @anishghimire603 @manavgakhar. Glad to know you are willing to work upon this issue
https://www.w3schools.com/howto/howto_css_loader.asp
https://stackoverflow.com/questions/40987309/react-display-loading-screen-while-dom-is-rendering
https://redstapler.co/add-loading-animation-to-website/
Here are some useful links that can help you get started, once you have done a bit of work we can discuss it over the PR also.

If you have some views & suggestions to add a more innovative loader you want to discuss, you can in the comments of the issues.

**Comment by Ask-Subhasmita** [comment]
Hi, this is my first open source comtribution , would you help me get started with it?
