### ISSUE TITLE
Unstructured list of Contributors

### ISSUE THREAD

**Issue by Suyash-Purwar** [codeforcauseorg/pledge#225]
I checked the code of this project and by cross-checking the list of the contributors JSON file with the displayed cards on the site, I realized that the cards are structured by the alphabetic ordering of the name of their respective JSON file. That means, say `Shubham.json` is displayed first then `ayush.json` because "capital S" is greater than "small a" in ASCII encoding.

I made a contribution to this project a day ago and I saved my JSON file with the name `suyash.json`. I went to the site to check my profile card. I was confused that my profile card was not mentioned even in the part where cards with the name S were starting. I scrolled further and cards with the name starting with A again started to appear. Following that, cards with the name starting with b, c, d, etc were listed. Almost at the very last of the page, I found my card.

This can cause confusion among beginners and they might even open a pull request saying "My profile card is not displayed". The number of contributors who took the pledge is about to reach 200 and I think this can happen. In fact, I was about to open an issue too.

I think cards should be arranged in alphabetical order without being case-sensitive. It should be arranged like that regardless of whether the contributor saves their JSON file with a capital letter or not. And a side note should be there on the website saying something like "Cards are arranged in the alphabetical order of contributors name" after this issue is fixed.

Alternatively, we can just take care of the upcoming contribution by adding one more point in the [create_pledge.md](https://github.com/codeforcauseorg/pledge/blob/master/hints/create_pledge.md) file stating that the JSON file must be named with only the first letter being capital so that the upcoming contributions are structured. But this would leave already made contributions unstructured.

Checking whether the first letter of the JSON file is capital or not during the time of PR can be automated with integration testing which is already in place. I am not sure about this though.

Thanks for reading! 😊

**Comment by PrathameshAshra** [comment]
While rendering, do you think we can sort it out by name on " data.allContributorsJson.edges "

**Comment by Pavankalyan0105** [comment]
Hi  , I would like to work on this issue , can you suggest me the way to get started?

**Comment by Pranay178** [comment]
hlo! I would like to work on this issue can u suggest me some tips

**Comment by PrathameshAshra** [comment]
> Hi , I would like to work on this issue , can you suggest me the way to get started?

Same here, still awaiting for their responses.

**Comment by Suyash-Purwar** [comment]
I think you guys should start and make a pull request.

**Comment by tejasjadhav1** [comment]
Hi

**Comment by tejasjadhav1** [comment]
How can i solve this issue

**Comment by PrajwalG22** [comment]
Hi, I am new here, and would like to work on the issue.
Suggest me the ways

**Comment by viki4545** [comment]
Hi, i would like to work on this issue, can you suggest me how to get started?

**Comment by AmanDw** [comment]
Hi, I would like to work on this issue, can you suggest me ways to get started  with this?

**Comment by KamalSinghKhanna** [comment]
Hi, I want to work on this issue, can you suggest me ways to get started?

**Comment by salmanprottoy** [comment]
Hi, I would like to work on this issue, can you suggest me ways to get started with this?

**Comment by PrincePandey1** [comment]
Hi, I would like to work on this issue, can you suggest me ways to get started with this?

**Comment by Parth-Shete** [comment]
Hi, I would like to work on this issue, can you suggest me ways to get started with this?

**Comment by priyaankamishra** [comment]
Hey ! I would like to work on this issue.

**Comment by SuryanshShahi** [comment]
Hi , I would like to work on this issue , can you suggest me the way to get started?

**Comment by balarka135** [comment]
I would like to work on this issue

**Comment by Shivam-45** [comment]
Hi, I would like to work on this issue,  can you guide me how to get started?

**Comment by SarthakSrivastav** [comment]
Hi , I would like to work on this issue , can you suggest me the way to get started?

**Comment by Shivam-45** [comment]
Yeah sure.
Do you need any video reference or something ? Because it's hard to type
the things here.

**Comment by SarthakSrivastav** [comment]
Hi, @Shivam-45 
I follow [this](https://www.youtube.com/watch?v=8pjxegUW7lQ&t=1538s) video and I'm trying to make my first full request which I successfully done and push it on github. Now I am waiting to merge my code from your side. 
Please merge it ASAP if all are good  so that I feel more confident that yessss I did it. 
Thankyou.

**Comment by Shivam-45** [comment]
Ok, I will check it out.

**Comment by Shivam-45** [comment]
Please make pull request also. So, that can merge it.

**Comment by ujjwal-sharma221** [comment]
Just a new github user passing by

**Comment by Shivam-45** [comment]
Ok do one thing .
Make a pull request on any of my repo.

https://github.com/Shivam-45

**Comment by HassanRahim26** [comment]
Hi, I am Hassan. I would like to work on this issue, can you suggest ways to get started?

**Comment by Ritikkumar992** [comment]
I want to work on this project can you help me

**Comment by starrohan999** [comment]
Hii I would like to work on the Demo issue, can you suggest to me ways to get started?

**Comment by nitinyadav78** [comment]
Hi, I would like to work on this issue, can you suggest me the way to get started?

**Comment by Nitesh639** [comment]
Hi, I would like to work on this issue, can you suggest me the way to get started?

**Comment by mkhulbe5** [comment]
Hi,i would like to work and to started of with open source thing, anyone here to guide me up?

**Comment by Ritikkumar992** [comment]
Hi,i would like to work and to started of with open source thing, anyone here to guide me up?

**Comment by Sajal0208** [comment]
HEy I would like to work on this issue

**Comment by ARSHADKHAN615** [comment]
kiya bolte publllic 😎😎

**Comment by HarshKumarSingh07** [comment]
Hey, I am beginner. Kindly guide me through the way forward.

**Comment by ARSHADKHAN615** [comment]
How can I help you brother

**Comment by gaurav-uk2001** [comment]
hey, i would like to work in this issue

**Comment by ZohebMOPO** [comment]
Hey Everyone. This is my first time contributing to open source.

**Comment by Aman-mnnit** [comment]
Hi i would like to fix this issue,can you please suggest me how to start?

**Comment by classickartik** [comment]
Hi , I would like to work on this issue , can you suggest me the way to get started?

**Comment by sim567** [comment]
Hi, I would like to work on this issue , can u suggest me the way to get started?
