### ISSUE TITLE
Demo issue

### ISSUE THREAD

**Issue by kunal-kushwaha** [codeforcauseorg/pledge#3]
Bug: Demo bug, something not working as expected

**Comment by kunal-kushwaha** [comment]
Hi, I would like to work on this issue, can you suggest me ways to get started?

**Comment by GangaChatrvedi** [comment]
Hi Kunal, you can try this and that

**Comment by SafiaKhaleel** [comment]
Hey.! I'm new to open source and wanted to try it out. Can I use this issue to get started

**Comment by warriorwizard** [comment]
hey buddy i wanna work on this project

**Comment by Jithendra-k** [comment]
hi , i want to work on this issue. could you suggest me a way

**Comment by itsmohamedghouse** [comment]
Hey I would like to work on this issue

**Comment by rohank2502** [comment]
Hey !1 Myself Rohan . I will like to contibute on open source community . Any guidance for a begginer

**Comment by RishabhChauhan22** [comment]
hi , i would like to work on this issue , can you suggest me some ways to get started ?

**Comment by theshivv** [comment]
Hi, I am Shivam.0 I would like to work on this issue, can you suggest ways to get started?

**Comment by rajulkoshta** [comment]
hi, I am new to the open source, I would like to work on this issue  can  someone suggest how to get started

**Comment by Pratham-Patel** [comment]
Hey! I am willing to work on this issue! Can you enjoin me to get started?

**Comment by Ghosling** [comment]
Hi, I would love to work on this issue.

**Comment by gaurav147-star** [comment]
Hi, I would like to work on this issue ,can you suggest me ways to get started?

**Comment by Sanu3007** [comment]
Hi, I am new to open-source . Can you help me get started and fix this issue ?

**Comment by AAB007209** [comment]
Hi guys, I am new to open source, I would like to work on this issue. Can anyone suggest me how to proceed and fix this issue?

**Comment by dikshanasa** [comment]
Hi, I would like to work on this issue, please suggest me how to get started.

**Comment by Sanyam17-beep** [comment]
i want to start please assign this issue to me
