### ISSUE TITLE
Demo Issue

### ISSUE THREAD

**Issue by SazanDawadi** [codeforcauseorg/pledge#305]
Demo bug ,something not working as intended

**Comment by iota-008** [comment]
https://pledge.codeforcause.org/ 
this link is not working , not showing anything for now.

**Comment by Soumava-221B** [comment]
Hi, I would like to work on this issue, can you suggest me ways to get started?

**Comment by Abhishek-kumar09** [comment]
Fixed With https://github.com/codeforcauseorg/pledge/commit/f0d9d89bdeb8886154493e98fe587c639b76f46f

**Comment by Abhishek-kumar09** [comment]
@iota-008 Site is up now.
