### ISSUE TITLE
Replace infinite scrolling with pagination for displaying pledge cards

### ISSUE THREAD

**Issue by darecoder** [codeforcauseorg/pledge#37]
**Describe the issue**
Add pagination feature for displaying pledge cards. It should display 39 cards/page (i.e. 13*3, 3 cards in a row) with all the pages mentioned below.

**Comment by Bijay555** [comment]
hi I would like to work on this issue. Can you suggest me how should I get started?

**Comment by palak199** [comment]
is it open still?

**Comment by NikkiPriya** [comment]
Hi, I would like to work on this issue, can you help me ways to get started?

**Comment by srishtipoudel** [comment]
Hi, I would like to work on this issue, can you suggest me ways to get started?

**Comment by srishtipoudel** [comment]
How do I reproduce this error?

**Comment by pandafy** [comment]
@srishtipoudel it is not an error. It is a feature which is needed to be added. Presently all cards are rendered at once on the webpage. This will increase loading time once there are ample number of pledges. 

The goal is to load only a specific number of card at once and then add page navigation to browse other cards. [Please do a lookup for pagination](https://www.google.com/search?q=pagination&oq=pagination&aqs=chrome..69i57j0l5j69i61l2.1409j0j7&client=ubuntu&sourceid=chrome&ie=UTF-8).

**Comment by codevfahad** [comment]
Hi, I would like to work on this issue, can you suggest me ways to get started?

**Comment by Rupeshkoushik** [comment]
Hi, I am a beginner to open source and I am super interested for contributing to open source. Can you suggest me ways to get started?

**Comment by darecoder** [comment]
> @srishtipoudel it is not an error. It is a feature which is needed to be added. Presently all cards are rendered at once on the webpage. This will increase loading time once there are ample number of pledges.
> 
> The goal is to load only a specific number of card at once and then add page navigation to browse other cards. [Please do a lookup for pagination](https://www.google.com/search?q=pagination&oq=pagination&aqs=chrome..69i57j0l5j69i61l2.1409j0j7&client=ubuntu&sourceid=chrome&ie=UTF-8).

@codevfahad @Rupeshkoushik refer to this comment and draft a PR for this. :)

**Comment by AkshatRastogi-1nC0re** [comment]
Hi I would like to work on this issue, Can you suggest me how to get started ?

**Comment by SimranjeetSingh5** [comment]
Hi I would like to contribute, Can you suggest to me how I could do so?

**Comment by kushagra-aa** [comment]
Hey, I would like to work on fixing the issue,
Can you suggest to me how to get started?

**Comment by yashss1** [comment]
Hi, I am new to Github, and very much intrested in learning new things.
Can u help me by suggesting how can i get started?

**Comment by rishabhthakur11** [comment]
Hey, I would like to work on fixing the issue,
Can you suggest to me how to get started?

**Comment by shivamrai1904** [comment]
hey there, i would like to work on this issue. Can you suggest me how to get started?

**Comment by shashankbhatgs123** [comment]
Hello everyone! I'm new to opensource. Can anyone guide me? 
Thank you

**Comment by shashankbhatgs123** [comment]
Hello everyone! I'm new to opensource but would like to work on this issue and will start from here. Can anyone guide me?
Thank you

**Comment by Devv14** [comment]
Hi. I am a new contributor and would like to work on this issue , can you suggest me ways to get started?

**Comment by Adityachaturvedi2906** [comment]
Hi, I would like to contribute to this issue, please guide me further.

**Comment by anshkhandelwal12** [comment]
Hii Friends I am actually Excited to Contribute on These Issue

**Comment by salmanprottoy** [comment]
Hey, I would like to work on fixing the issue, can you suggest to me how to get started?

**Comment by iota-008** [comment]
I would like to work on this feature.

**Comment by iota-008** [comment]
i have created to pull request to add pagination please check and verify.
it has passed all checks

**Comment by Ritikkumar992** [comment]
Can I work on this project.

**Comment by Soumokanti123** [comment]
Hi, I would like to fix this issue. Can I take part??

**Comment by s-mahesh-kumar** [comment]
what do you think are the prerequisites for fixing this issue can you please list it out ?

**Comment by BharatChotwani** [comment]
Hello, I would like to work on this issue, can you suggest me ways to get started?

**Comment by jatinS-dev** [comment]
Hi, I would like to contribute to this issue, please guide me further.

**Comment by CYBER-BRIX** [comment]
hey can you assign this issue to me .

**Comment by abhijeetdav24aug** [comment]
Hi, I want to work on this issue. Can u suggest ways to get started?

**Comment by Abhishek-kumar09** [comment]
Sorry @abhijeetdav24aug The fix is merged! Thanks for stopping by.
If you want to contribute to other open source projects, you can do by looking to some other projects like click-short, causefolio, certificate-generator-react, edu-server, and many more :smile:
