### ISSUE TITLE
Create detailed readme file 

### ISSUE THREAD

**Issue by BrundaBR** [codeforcauseorg/pledge#437]
Creating a readme file which involves all steps for a student who is making his/her first contribution,as readme.md is not as detailed.

**Comment by Karthik-59** [comment]
Hi @BrundaBR can I take this issue ?

**Comment by BrundaBR** [comment]
Hey @Karthik-59  i am already working on this issue

**Comment by 0verlord7776** [comment]
Hi, I would like to work on this issue.

**Comment by 2911rahulpathak** [comment]
Hi, I would like to work on this issue

**Comment by Tejas-r281** [comment]
hey , i would like to work on this issue
