### ISSUE TITLE
Demo Title

### ISSUE THREAD

**Issue by Yamini09-code** [codeforcauseorg/pledge#513]
Hey, I am new to open source and looking forward to becoming a valuable part of this community.
#My first PR

**Comment by sigma101-hub** [comment]
@Yamii09-code Me too

**Comment by KholoodS** [comment]
Hi I would like to work on this issue

**Comment by yashkondajisonawane** [comment]
i want to work on this issue

**Comment by vedantsaraf2002** [comment]
I want to work on this issue

**Comment by abhijeetdav24aug** [comment]
Hi, would like to work on this issue.

**Comment by vdas01** [comment]
Hii, I am new to open-source and looking ahead to contribute..!!

**Comment by Sanyam17-beep** [comment]
hi i would like to contribute

**Comment by amruth-acharya** [comment]
I am newbie into opensource and glad that I found code for cause.

**Comment by Abhishek-kumar09** [comment]
Thanks for stopping by everyone.
If you want to contribute, you can contribute to other open source projects like click-short, causefolio, certificate-generator-react, edu-server, and many more :smiley: 
Looking forward to it :champagne:

**Comment by si88hant** [comment]
Hi all, I am new to open source. Thank you code for cause 😀

**Comment by Dnyaneshwari931** [comment]
Hi, I'm new to open source contribution so thank you for this cause, looking forward for more such initiative...

**Comment by adilpasha-projects** [comment]
Hi, I would like to work on this issue ,can you suggest me ways to get started?

**Comment by itsmesuman** [comment]
Hi, I am new to open source and I would like to work on this issue, please suggest me ways to get started?

**Comment by Shofiya2003** [comment]
Hi, I would like to work on this issue, can you suggest me ways to get started?

**Comment by Abhishek-kumar09** [comment]
This is not a valid issue. Closing it for now.
If you want to start with some issues. Create your pledge :smile: 
The steps to create a pledge card is discussed in Readme.md file.

Thanks for stopping by.
